In [2]:
from dask import dataframe as df
import pandas as pd
import functools as ft

In [3]:
dask_df1 = df.read_csv('title_akas.tsv', sep ='\t', dtype={'isOriginalTitle': 'object'})
dask_df2 = df.read_csv('title_basics.tsv', sep ='\t', dtype={'runtimeMinutes': 'object',
       'startYear': 'object', 'isAdult': 'object'})
dask_df3 = df.read_csv('title_rating.tsv', sep ='\t')

In [4]:
dask_df1 = dask_df1.rename(columns={'titleId':'tconst'})
dask_df1.head()

,tconst,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Карменсіта,UA,\N,imdbDisplay,\N,0
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
3,tt0000001,4,Καρμενσίτα,GR,\N,imdbDisplay,\N,0
4,tt0000001,5,Карменсита,RU,\N,imdbDisplay,\N,0

In [5]:
dask_df2.head(1000)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
995,tt0001007,movie,La primera y segunda casetas,La primera y segunda casetas,0,1909,\N,\N,\N
996,tt0001008,short,The Prince and the Pauper,The Prince and the Pauper,0,1909,\N,\N,Short
997,tt0001009,short,"Princess Nicotine; or, the Smoke Fairy","Princess Nicotine; or, The Smoke Fairy",0,1909,\N,5,"Comedy,Fantasy,Short"
998,tt0001010,movie,Protección de un convoy de víveres en el puent...,Protección de un convoy de víveres en el puent...,0,1909,\N,\N,\N
999,tt0001011,short,The Prussian Spy,The Prussian Spy,0,1909,\N,5,"Drama,Short"

In [6]:
dask_df3.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      1924
1  tt0000002            5.8       260
2  tt0000003            6.5      1736
3  tt0000004            5.6       175
4  tt0000005            6.2      2551

In [7]:
dask_df = dask_df1.merge(dask_df2, how = 'left', on = 'tconst')

In [8]:
dff = dask_df.merge(dask_df3, how = 'left', on = 'tconst')

In [8]:
dff.head()

KeyboardInterrupt:

In [9]:
dff.columns

Index(['tconst', 'ordering', 'title', 'region', 'language', 'types',
       'attributes', 'isOriginalTitle', 'titleType', 'primaryTitle',
       'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes',
       'genres', 'averageRating', 'numVotes'],
      dtype='object')

In [10]:
dff = dff.drop(['ordering', 'region', 'attributes', 'isOriginalTitle', 'types', 'primaryTitle',
       'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes'], axis = 1)

In [11]:
dff.head()

,tconst,title,language,titleType,genres,averageRating,numVotes
0,tt2919466,Don't Call Me Bambino,\N,movie,"Action,Adventure,Animation",5.4,11.0
1,tt2919502,Portico Books' Good Reading Guide,\N,tvEpisode,"Family,Talk-Show",NaN,NaN
2,tt2919798,En sag for mr. Whicher: Mordet i Angel Lane,\N,tvEpisode,"Crime,Drama,History",7.3,1203.0
3,tt2919798,The Murder in Angel Lane,\N,tvEpisode,"Crime,Drama,History",7.3,1203.0
4,tt2919798,Podejrzenia pana Whichera: Morderstwo na Angel...,\N,tvEpisode,"Crime,Drama,History",7.3,1203.0

In [12]:
dff1 = dff[dff['titleType']=='movie']

In [13]:
dff1.head()

,tconst,title,language,titleType,genres,averageRating,numVotes
334,tt4756228,Star Trek 14,\N,movie,"Action,Adventure,Mystery",NaN,NaN
335,tt4756228,Untitled Star Trek Sequel,\N,movie,"Action,Adventure,Mystery",NaN,NaN
336,tt4756228,Звёздный путь 4,\N,movie,"Action,Adventure,Mystery",NaN,NaN
337,tt4756228,Star Trek 4,\N,movie,"Action,Adventure,Mystery",NaN,NaN
338,tt4756228,Untitled Star Trek Sequel,\N,movie,"Action,Adventure,Mystery",NaN,NaN

In [13]:
len(dff1)

2746779

In [17]:
dff2 = dff1.dropna()

In [18]:
len(dff2)

2070465

In [20]:
dff2.to_csv("data.csv", index=False, single_file=True)

['d:\\Dataset\\IMDb\\data.csv']